<?php

use Magento\Framework\App\ActionInterface;

$title = $block->getConfigValue('title');
$mode = $block->getConfigValue('display_mode');

$class = ($mode == 'slider') ? 'cc-product-slider' : 'cc-product-grid';

$image = 'product_base_image';

$showAddTo = true;
$showCart = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$description = ($mode == 'list') ? true : false;

/** @var \Conceptive\ProductSlider\Block\ProductList $block */
$_items = $block->getProductCollection();

?>

<?php if ($_items->getSize()): ?>
    <div class="block widget <?= $block->escapeHtmlAttr($class) ?>">
        <div class="block-title">
            <div class="content-heading">
                <div class="title"><?= $block->escapeHtml($title) ?></div>
            </div>
        </div>
      
        <div class="block-content">
            <div class="products wrapper grid products-grid">
                <ol class="products list items product-items">
                    <?php foreach ($_items as $_item): ?>
                        <li class="item product product-item">
                            <div class="product-item-info">
                                <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                <a href="<?= $block->escapeUrl($_item->getProductUrl()) ?>" 
                                   class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                                title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                                href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>

                                    <?php if ($templateType):?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                                    <?= $block->getProductDetailsHtml($_item) ?>

                                    <?php if ($showAddTo || $showCart):?>
                                        <?php // phpcs:disable ?>
                                        <?php if ($mode != 'slider'): ?>
                                            <div class="product-item-inner">
                                        <?php endif; ?>
                                            <div class="product actions product-item-actions">
                                                <?php if ($showCart):?>
                                                    <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()):?>
                                                        <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)):?>
                                                            <button
                                                                    class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php else :?>
                                                            <?php
                                                            $postArray = $block->getAddToCartPostParams($_item);

                                                            $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                            ?>
                                                            <form data-role="tocart-form"
                                                                data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                                action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                                method="post">
                                                                <input type="hidden" name="product"
                                                                    value="<?= /* @noEscape */ (int)$_item->getEntityId() ?>">
                                                                <input type="hidden"
                                                                    name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED?>"
                                                                    value="<?= /* @noEscape */ $value ?>">
                                                                <?= $block->getBlockHtml('formkey') ?>
                                                                <button type="submit"
                                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                        class="action tocart primary">
                                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                </button>
                                                            </form>
                                                        <?php endif; ?>
                                                    <?php else:?>
                                                        <?php if ($_item->isAvailable()):?>
                                                            <div class="stock available">
                                                                <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                            </div>
                                                        <?php else:?>
                                                            <div class="stock unavailable">
                                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>

                                                <?php if ($showAddTo):?>
                                                    <div class="secondary-addto-links actions-secondary"
                                                        data-role="add-to-links">
                                                        <?php if ($addToBlock = $block->getChildBlock('addto')):?>
                                                            <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php if ($mode != 'slider'): ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php // phpcs:enable ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
    </div>
<?php else: ?>
    <p><?= __('No products found.') ?></p>
<?php endif; ?>

<script>
require(['jquery', 'slick'], function($){
    $(document).ready(function() {
        $('.cc-product-slider .product-items').slick({
            dots: true,
            infinite: true,
            slidesToShow: 5,
            slidesToScroll: 1,
            autoplay: true,
            responsive: [
                {
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: 5,
                        slidesToScroll: 1,
                        infinite: true,
                        dots: true
                    }
                },
                {
                    breakpoint: 992,
                    settings: {
                        slidesToShow: 4,
                        slidesToScroll: 1
                    }
                },
                {
                    breakpoint: 769,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 1
                    }
                },
                {
                    breakpoint: 640,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 1
                    }
                }
            ],
        });
    });
});
</script>

<style>
    .cc-product-slider .products-grid .product-item-actions{
        margin-top: 0;
    }
    /* the slides */
    .cc-product-slider .slick-slide {
        margin: 10px 15px 0;
    }

    /* the parent */
    .cc-product-slider .slick-list {
        margin: 0 -15px;
    }
</style>
